package Vista;

public class compras extends javax.swing.JFrame {

    public compras() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLregresar, jPregresar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPregresar = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTFestableCREAR = new javax.swing.JTextField();
        jTFdireccCREAR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFffechaEgresCREAR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFinstiCREAR = new javax.swing.JTextField();
        jTFnomGenCREAR = new javax.swing.JTextField();
        jTFnomComCREAR = new javax.swing.JTextField();
        jTFformaCREAR = new javax.swing.JTextField();
        jTFitemCREAR = new javax.swing.JTextField();
        jTFpresentacionCREAR = new javax.swing.JTextField();
        jTFloteCREAR = new javax.swing.JTextField();
        jTFfechaExpCREAR = new javax.swing.JTextField();
        jTFcantidadCREAR = new javax.swing.JTextField();
        jTFobservacionesCREAR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTFcumCREAR1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTFcalculoCREAR = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTFestableciBUS = new javax.swing.JTextField();
        jTFdireccionBUS = new javax.swing.JTextField();
        jTFfechaEgresoBUS = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTFinstiBUS = new javax.swing.JTextField();
        jTFobservaBUS = new javax.swing.JTextField();
        jTFnomGenBUS = new javax.swing.JTextField();
        jTFnomComBUS = new javax.swing.JTextField();
        jTFformaBUS = new javax.swing.JTextField();
        jTFitemBUS = new javax.swing.JTextField();
        jTFpresentacionBUS = new javax.swing.JTextField();
        jTFloteBUS = new javax.swing.JTextField();
        jTFfechaExpBUS = new javax.swing.JTextField();
        jTFcantidadBUS = new javax.swing.JTextField();
        jTFcalculoBUS = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPbuscar = new javax.swing.JPanel();
        jLbuscar2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPbuscar1 = new javax.swing.JPanel();
        jLbuscar1 = new javax.swing.JLabel();
        jLbuscar = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTFcumBUS1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTFestableACT = new javax.swing.JTextField();
        jTFdireccionACT = new javax.swing.JTextField();
        jTFfechaEgresoACT = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTFinstiACT = new javax.swing.JTextField();
        jTFobservacionesACT = new javax.swing.JTextField();
        jTFnomGenACT = new javax.swing.JTextField();
        jTFnomComACT = new javax.swing.JTextField();
        jTFformaACT = new javax.swing.JTextField();
        jTFitemACT = new javax.swing.JTextField();
        jTFpresentacionACT = new javax.swing.JTextField();
        jTFloteACT = new javax.swing.JTextField();
        jTFfechaExpACT = new javax.swing.JTextField();
        jTFcantidadACT = new javax.swing.JTextField();
        jTFcalculoACT = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPbuscarACT = new javax.swing.JPanel();
        jLbuscarACT = new javax.swing.JLabel();
        jPactualizarACT = new javax.swing.JPanel();
        jLactualizarACT = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTFcumACT1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jTFestableBORR = new javax.swing.JTextField();
        jTFdireccionBORR = new javax.swing.JTextField();
        jTFfechaEgresoBORR = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTFinstiBORR = new javax.swing.JTextField();
        jTFobservacionesBORR = new javax.swing.JTextField();
        jTFnomGenBORR = new javax.swing.JTextField();
        jTFnomComBORR = new javax.swing.JTextField();
        jTFformaBORR = new javax.swing.JTextField();
        jTFitemBORR = new javax.swing.JTextField();
        jTFpresentacionBORR = new javax.swing.JTextField();
        jTFloteBORR = new javax.swing.JTextField();
        jTFfechaExpBORR = new javax.swing.JTextField();
        jTFcantidadBORR = new javax.swing.JTextField();
        jTFcalculoBORR = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPbuscarBORR = new javax.swing.JPanel();
        jLbuscarBORR = new javax.swing.JLabel();
        jPborrarBORR = new javax.swing.JPanel();
        jLborrarBORR = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jTFcumBORR1 = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        jLabel3.setText("HOSPITAL EPN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel3.setBackground(new java.awt.Color(0, 134, 190));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COMPRAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        jPregresar.setBackground(new java.awt.Color(153, 204, 255));

        jLregresar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLregresar.setForeground(new java.awt.Color(255, 255, 255));
        jLregresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLregresar.setText("REGRESAR");
        jLregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLregresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPregresarLayout = new javax.swing.GroupLayout(jPregresar);
        jPregresar.setLayout(jPregresarLayout);
        jPregresarLayout.setHorizontalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLregresar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPregresarLayout.setVerticalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLregresar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 150, 30));

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos del Producto");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Establecimiento");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jTFestableCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFestableCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFestableCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFdireccCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdireccCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFdireccCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Dirección");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha  Preparacion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jTFffechaEgresCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFffechaEgresCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFffechaEgresCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));

        jLabel4.setText("Datos de Destinatario");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Institución");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nombre Generico");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nombre Comercial");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Forma Farmaceutica");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jTFinstiCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFinstiCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFinstiCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFnomGenCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFnomGenCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        jTFnomComCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFnomComCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jTFformaCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFformaCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jTFitemCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFitemCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFitemCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTFpresentacionCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFpresentacionCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, -1));

        jTFloteCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFloteCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, -1));

        jTFfechaExpCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFfechaExpCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, -1));

        jTFcantidadCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFcantidadCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 250, -1));

        jTFobservacionesCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFobservacionesCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFobservacionesCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 250, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Item");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Presentacion");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Lote");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Fecha exp.");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Cantidad");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Observaciones");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 20));

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("NUEVO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 350, 30));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CREAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Institucion", "Establecimiento", "Direccion", "Fecha Preparacion", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Calculo", "Observaciones"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("CUM/CUDIM");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jTFcumCREAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumCREAR1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTFcumCREAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Calculo");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        jTFcalculoCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcalculoCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFcalculoCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, -1));

        jTabbedPane1.addTab("Crear", jPanel2);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Datos del Producto");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel9.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 780, 10));

        jTFestableciBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFestableciBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFestableciBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFdireccionBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdireccionBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFdireccionBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jTFfechaEgresoBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaEgresoBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFfechaEgresoBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));
        jPanel9.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Observaciones");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Nombre Genrico");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Nombre Comercial");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Forma Farmaceutica");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jTFinstiBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFinstiBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFinstiBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFobservaBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFobservaBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFobservaBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 250, -1));

        jTFnomGenBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFnomGenBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 250, -1));

        jTFnomComBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFnomComBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 250, -1));

        jTFformaBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFformaBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 250, -1));

        jTFitemBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFitemBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFitemBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, -1));

        jTFpresentacionBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFpresentacionBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 250, -1));

        jTFloteBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFloteBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 250, -1));

        jTFfechaExpBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFfechaExpBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 250, -1));

        jTFcantidadBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFcantidadBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 250, -1));

        jTFcalculoBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcalculoBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFcalculoBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 250, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Item");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Presentacion");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 20));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Lote");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, 20));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("Fecha exp.");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 20));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Cantidad");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Calculo");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, 20));

        jPbuscar.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscar2.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscar2.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscarLayout = new javax.swing.GroupLayout(jPbuscar);
        jPbuscar.setLayout(jPbuscarLayout);
        jPbuscarLayout.setHorizontalGroup(
            jPbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPbuscarLayout.setVerticalGroup(
            jPbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 30));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane11.setBackground(new java.awt.Color(255, 255, 255));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Institucion", "Establecimiento", "Direccion", "Fecha Preparacion", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Calculo", "Observaciones"
            }
        ));
        jScrollPane11.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane3.setViewportView(jScrollPane11);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jPbuscar1.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscar1.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscar1.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscar1Layout = new javax.swing.GroupLayout(jPbuscar1);
        jPbuscar1.setLayout(jPbuscar1Layout);
        jPbuscar1Layout.setHorizontalGroup(
            jPbuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPbuscar1Layout.setVerticalGroup(
            jPbuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 780, 30));

        jLbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscar.setText("BUSCAR");
        jPanel9.add(jLbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 30));

        jLabel73.setText("Datos de Destinatario");
        jPanel9.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel74.setText("Institución");
        jPanel9.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel75.setText("Establecimiento");
        jPanel9.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel76.setText("Dirección");
        jPanel9.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel77.setText("Fecha de Egreso");
        jPanel9.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("CUM/CUDIM");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jTFcumBUS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumBUS1ActionPerformed(evt);
            }
        });
        jPanel9.add(jTFcumBUS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 250, -1));

        jTabbedPane1.addTab("Buscar", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setText("Datos del Producto");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel10.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 10));

        jTFestableACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFestableACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFestableACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFdireccionACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdireccionACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFdireccionACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jTFfechaEgresoACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaEgresoACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFfechaEgresoACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));
        jPanel10.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("Observaciones");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 20));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setText("Nombre Genrico");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setText("Nombre Comercial");
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Forma Farmaceutica");
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jTFinstiACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFinstiACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFinstiACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFobservacionesACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFobservacionesACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFobservacionesACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 250, -1));

        jTFnomGenACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFnomGenACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        jTFnomComACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFnomComACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jTFformaACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFformaACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jTFitemACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFitemACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFitemACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTFpresentacionACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFpresentacionACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, -1));

        jTFloteACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFloteACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, -1));

        jTFfechaExpACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFfechaExpACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, -1));

        jTFcantidadACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFcantidadACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 250, -1));

        jTFcalculoACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcalculoACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFcalculoACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Item");
        jPanel10.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Presentacion");
        jPanel10.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setText("Lote");
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setText("Fecha exp.");
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 20));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("Cantidad");
        jPanel10.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Calculo");
        jPanel10.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane12.setBackground(new java.awt.Color(255, 255, 255));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Institucion", "Establecimiento", "Direccion", "Fecha Preparacion", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Calculo", "Observaciones"
            }
        ));
        jScrollPane12.setViewportView(jTable6);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane5.setViewportView(jScrollPane12);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jPbuscarACT.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscarACT.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscarACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarACT.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscarACTLayout = new javax.swing.GroupLayout(jPbuscarACT);
        jPbuscarACT.setLayout(jPbuscarACTLayout);
        jPbuscarACTLayout.setHorizontalGroup(
            jPbuscarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPbuscarACTLayout.setVerticalGroup(
            jPbuscarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPbuscarACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 30));

        jPactualizarACT.setBackground(new java.awt.Color(153, 204, 255));

        jLactualizarACT.setForeground(new java.awt.Color(255, 255, 255));
        jLactualizarACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLactualizarACT.setText("ACTUALIZAR");

        javax.swing.GroupLayout jPactualizarACTLayout = new javax.swing.GroupLayout(jPactualizarACT);
        jPactualizarACT.setLayout(jPactualizarACTLayout);
        jPactualizarACTLayout.setHorizontalGroup(
            jPactualizarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLactualizarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPactualizarACTLayout.setVerticalGroup(
            jPactualizarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLactualizarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPactualizarACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 350, 30));

        jLabel78.setText("Datos de Destinatario");
        jPanel10.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel80.setText("Institución");
        jPanel10.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel82.setText("Establecimiento");
        jPanel10.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel84.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel84.setText("Dirección");
        jPanel10.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel86.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel86.setText("Fecha de Egreso");
        jPanel10.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("CUM/CUDIM");
        jPanel10.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jTFcumACT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumACT1ActionPerformed(evt);
            }
        });
        jPanel10.add(jTFcumACT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jTabbedPane1.addTab("Actualizar", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setText("Datos del Producto");
        jPanel11.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel11.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 10));

        jTFestableBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFestableBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFestableBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFdireccionBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdireccionBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFdireccionBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jTFfechaEgresoBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaEgresoBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFfechaEgresoBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));
        jPanel11.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel63.setText("Observaciones");
        jPanel11.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 20));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel64.setText("Nombre Genrico");
        jPanel11.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setText("Nombre Comercial");
        jPanel11.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("Forma Farmaceutica");
        jPanel11.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jTFinstiBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFinstiBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFinstiBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFobservacionesBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFobservacionesBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFobservacionesBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 250, -1));

        jTFnomGenBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFnomGenBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        jTFnomComBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFnomComBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jTFformaBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFformaBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jTFitemBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFitemBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFitemBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTFpresentacionBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFpresentacionBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, -1));

        jTFloteBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFloteBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, -1));

        jTFfechaExpBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFfechaExpBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, -1));

        jTFcantidadBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFcantidadBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 250, -1));

        jTFcalculoBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcalculoBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFcalculoBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel67.setText("Item");
        jPanel11.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel68.setText("Presentacion");
        jPanel11.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel69.setText("Lote");
        jPanel11.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel70.setText("Fecha exp.");
        jPanel11.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 20));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel71.setText("Cantidad");
        jPanel11.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel72.setText("Calculo");
        jPanel11.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane13.setBackground(new java.awt.Color(255, 255, 255));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Institucion", "Establecimiento", "Direccion", "Fecha Preparacion", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Calculo", "Observaciones"
            }
        ));
        jScrollPane13.setViewportView(jTable7);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane7.setViewportView(jScrollPane13);

        jPanel11.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jPbuscarBORR.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscarBORR.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscarBORR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarBORR.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscarBORRLayout = new javax.swing.GroupLayout(jPbuscarBORR);
        jPbuscarBORR.setLayout(jPbuscarBORRLayout);
        jPbuscarBORRLayout.setHorizontalGroup(
            jPbuscarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPbuscarBORRLayout.setVerticalGroup(
            jPbuscarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel11.add(jPbuscarBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 30));

        jPborrarBORR.setBackground(new java.awt.Color(153, 204, 255));

        jLborrarBORR.setForeground(new java.awt.Color(255, 255, 255));
        jLborrarBORR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLborrarBORR.setText("BORRAR");

        javax.swing.GroupLayout jPborrarBORRLayout = new javax.swing.GroupLayout(jPborrarBORR);
        jPborrarBORR.setLayout(jPborrarBORRLayout);
        jPborrarBORRLayout.setHorizontalGroup(
            jPborrarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLborrarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPborrarBORRLayout.setVerticalGroup(
            jPborrarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLborrarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel11.add(jPborrarBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 350, 30));

        jLabel79.setText("Datos de Destinatario");
        jPanel11.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel81.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel81.setText("Institución");
        jPanel11.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel83.setText("Establecimiento");
        jPanel11.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel85.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel85.setText("Dirección");
        jPanel11.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel87.setText("Fecha de Egreso");
        jPanel11.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jTFcumBORR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumBORR1ActionPerformed(evt);
            }
        });
        jPanel11.add(jTFcumBORR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel88.setText("CUM/CUDIM");
        jPanel11.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jTabbedPane1.addTab("Borrar", jPanel11);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLregresarMouseClicked

        JFmenuInventario regre = new JFmenuInventario();
        regre.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLregresarMouseClicked

    private void jTFestableCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFestableCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFestableCREARActionPerformed

    private void jTFdireccCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdireccCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdireccCREARActionPerformed

    private void jTFffechaEgresCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFffechaEgresCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFffechaEgresCREARActionPerformed

    private void jTFinstiCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFinstiCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFinstiCREARActionPerformed

    private void jTFnomGenCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenCREARActionPerformed

    private void jTFnomComCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComCREARActionPerformed

    private void jTFformaCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaCREARActionPerformed

    private void jTFitemCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFitemCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFitemCREARActionPerformed

    private void jTFpresentacionCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionCREARActionPerformed

    private void jTFloteCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteCREARActionPerformed

    private void jTFfechaExpCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpCREARActionPerformed

    private void jTFcantidadCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadCREARActionPerformed

    private void jTFobservacionesCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFobservacionesCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFobservacionesCREARActionPerformed

    private void jTFestableciBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFestableciBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFestableciBUSActionPerformed

    private void jTFdireccionBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdireccionBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdireccionBUSActionPerformed

    private void jTFfechaEgresoBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaEgresoBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaEgresoBUSActionPerformed

    private void jTFinstiBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFinstiBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFinstiBUSActionPerformed

    private void jTFobservaBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFobservaBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFobservaBUSActionPerformed

    private void jTFnomGenBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenBUSActionPerformed

    private void jTFnomComBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComBUSActionPerformed

    private void jTFformaBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaBUSActionPerformed

    private void jTFitemBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFitemBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFitemBUSActionPerformed

    private void jTFpresentacionBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionBUSActionPerformed

    private void jTFloteBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteBUSActionPerformed

    private void jTFfechaExpBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpBUSActionPerformed

    private void jTFcantidadBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadBUSActionPerformed

    private void jTFcalculoBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcalculoBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcalculoBUSActionPerformed

    private void jTFestableACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFestableACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFestableACTActionPerformed

    private void jTFdireccionACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdireccionACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdireccionACTActionPerformed

    private void jTFfechaEgresoACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaEgresoACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaEgresoACTActionPerformed

    private void jTFinstiACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFinstiACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFinstiACTActionPerformed

    private void jTFobservacionesACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFobservacionesACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFobservacionesACTActionPerformed

    private void jTFnomGenACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenACTActionPerformed

    private void jTFnomComACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComACTActionPerformed

    private void jTFformaACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaACTActionPerformed

    private void jTFitemACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFitemACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFitemACTActionPerformed

    private void jTFpresentacionACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionACTActionPerformed

    private void jTFloteACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteACTActionPerformed

    private void jTFfechaExpACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpACTActionPerformed

    private void jTFcantidadACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadACTActionPerformed

    private void jTFcalculoACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcalculoACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcalculoACTActionPerformed

    private void jTFestableBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFestableBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFestableBORRActionPerformed

    private void jTFdireccionBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdireccionBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdireccionBORRActionPerformed

    private void jTFfechaEgresoBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaEgresoBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaEgresoBORRActionPerformed

    private void jTFinstiBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFinstiBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFinstiBORRActionPerformed

    private void jTFobservacionesBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFobservacionesBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFobservacionesBORRActionPerformed

    private void jTFnomGenBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenBORRActionPerformed

    private void jTFnomComBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComBORRActionPerformed

    private void jTFformaBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaBORRActionPerformed

    private void jTFitemBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFitemBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFitemBORRActionPerformed

    private void jTFpresentacionBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionBORRActionPerformed

    private void jTFloteBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteBORRActionPerformed

    private void jTFfechaExpBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpBORRActionPerformed

    private void jTFcantidadBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadBORRActionPerformed

    private void jTFcalculoBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcalculoBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcalculoBORRActionPerformed

    private void jTFcumCREAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumCREAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumCREAR1ActionPerformed

    private void jTFcumBUS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumBUS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumBUS1ActionPerformed

    private void jTFcalculoCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcalculoCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcalculoCREARActionPerformed

    private void jTFcumACT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumACT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumACT1ActionPerformed

    private void jTFcumBORR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumBORR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumBORR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLactualizarACT;
    private javax.swing.JLabel jLborrarBORR;
    private javax.swing.JLabel jLbuscar;
    private javax.swing.JLabel jLbuscar1;
    private javax.swing.JLabel jLbuscar2;
    private javax.swing.JLabel jLbuscarACT;
    private javax.swing.JLabel jLbuscarBORR;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JPanel jPactualizarACT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPborrarBORR;
    private javax.swing.JPanel jPbuscar;
    private javax.swing.JPanel jPbuscar1;
    private javax.swing.JPanel jPbuscarACT;
    private javax.swing.JPanel jPbuscarBORR;
    private javax.swing.JPanel jPregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTFcalculoACT;
    private javax.swing.JTextField jTFcalculoBORR;
    private javax.swing.JTextField jTFcalculoBUS;
    private javax.swing.JTextField jTFcalculoCREAR;
    private javax.swing.JTextField jTFcantidadACT;
    private javax.swing.JTextField jTFcantidadBORR;
    private javax.swing.JTextField jTFcantidadBUS;
    private javax.swing.JTextField jTFcantidadCREAR;
    private javax.swing.JTextField jTFcumACT1;
    private javax.swing.JTextField jTFcumBORR1;
    private javax.swing.JTextField jTFcumBUS1;
    private javax.swing.JTextField jTFcumCREAR1;
    private javax.swing.JTextField jTFdireccCREAR;
    private javax.swing.JTextField jTFdireccionACT;
    private javax.swing.JTextField jTFdireccionBORR;
    private javax.swing.JTextField jTFdireccionBUS;
    private javax.swing.JTextField jTFestableACT;
    private javax.swing.JTextField jTFestableBORR;
    private javax.swing.JTextField jTFestableCREAR;
    private javax.swing.JTextField jTFestableciBUS;
    private javax.swing.JTextField jTFfechaEgresoACT;
    private javax.swing.JTextField jTFfechaEgresoBORR;
    private javax.swing.JTextField jTFfechaEgresoBUS;
    private javax.swing.JTextField jTFfechaExpACT;
    private javax.swing.JTextField jTFfechaExpBORR;
    private javax.swing.JTextField jTFfechaExpBUS;
    private javax.swing.JTextField jTFfechaExpCREAR;
    private javax.swing.JTextField jTFffechaEgresCREAR;
    private javax.swing.JTextField jTFformaACT;
    private javax.swing.JTextField jTFformaBORR;
    private javax.swing.JTextField jTFformaBUS;
    private javax.swing.JTextField jTFformaCREAR;
    private javax.swing.JTextField jTFinstiACT;
    private javax.swing.JTextField jTFinstiBORR;
    private javax.swing.JTextField jTFinstiBUS;
    private javax.swing.JTextField jTFinstiCREAR;
    private javax.swing.JTextField jTFitemACT;
    private javax.swing.JTextField jTFitemBORR;
    private javax.swing.JTextField jTFitemBUS;
    private javax.swing.JTextField jTFitemCREAR;
    private javax.swing.JTextField jTFloteACT;
    private javax.swing.JTextField jTFloteBORR;
    private javax.swing.JTextField jTFloteBUS;
    private javax.swing.JTextField jTFloteCREAR;
    private javax.swing.JTextField jTFnomComACT;
    private javax.swing.JTextField jTFnomComBORR;
    private javax.swing.JTextField jTFnomComBUS;
    private javax.swing.JTextField jTFnomComCREAR;
    private javax.swing.JTextField jTFnomGenACT;
    private javax.swing.JTextField jTFnomGenBORR;
    private javax.swing.JTextField jTFnomGenBUS;
    private javax.swing.JTextField jTFnomGenCREAR;
    private javax.swing.JTextField jTFobservaBUS;
    private javax.swing.JTextField jTFobservacionesACT;
    private javax.swing.JTextField jTFobservacionesBORR;
    private javax.swing.JTextField jTFobservacionesCREAR;
    private javax.swing.JTextField jTFpresentacionACT;
    private javax.swing.JTextField jTFpresentacionBORR;
    private javax.swing.JTextField jTFpresentacionBUS;
    private javax.swing.JTextField jTFpresentacionCREAR;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    // End of variables declaration//GEN-END:variables
}
