package Vista;

public class ingresos extends javax.swing.JFrame {

    public ingresos() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLregresar, jPregresar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPregresar = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFconcentracionCREAR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFrepresentanteCREAR = new javax.swing.JTextField();
        jTFnoFacCREAR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFfechaIngresoCREAR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFproveedorCREAR = new javax.swing.JTextField();
        jTFvalorTotalCREAR = new javax.swing.JTextField();
        jTFnomGenCREAR = new javax.swing.JTextField();
        jTFnomComCREAR = new javax.swing.JTextField();
        jTFformaCREAR = new javax.swing.JTextField();
        jTFcumCREAR = new javax.swing.JTextField();
        jTFpresentacionCREAR = new javax.swing.JTextField();
        jTFloteCREAR = new javax.swing.JTextField();
        jTFfechaExpCREAR = new javax.swing.JTextField();
        jTFcantidadCREAR = new javax.swing.JTextField();
        jTFvalorUnitCREAR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTFconcentracionBUS = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFrepresentanteBUS = new javax.swing.JTextField();
        jTFnoFacBUS = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTFfechaIngresoBUS = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTFproveedorBUS = new javax.swing.JTextField();
        jTFvalorTotalBUS = new javax.swing.JTextField();
        jTFnomGenBUS = new javax.swing.JTextField();
        jTFnomComBUS = new javax.swing.JTextField();
        jTFformaBUS = new javax.swing.JTextField();
        jTFcumBUS = new javax.swing.JTextField();
        jTFpresentacionBUS = new javax.swing.JTextField();
        jTFloteBUS = new javax.swing.JTextField();
        jTFfechaExpBUS = new javax.swing.JTextField();
        jTFcantidadBUS = new javax.swing.JTextField();
        jTFvalorUnitBUS = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPbuscar = new javax.swing.JPanel();
        jLbuscar2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPbuscar1 = new javax.swing.JPanel();
        jLbuscar1 = new javax.swing.JLabel();
        jLbuscar = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTFconcentracionACT = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTFrepresentanteACT = new javax.swing.JTextField();
        jTFnoFacACT = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTFfechaIngresoACT = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTFproveedorACT = new javax.swing.JTextField();
        jTFvalorTotalACT = new javax.swing.JTextField();
        jTFnomGenACT = new javax.swing.JTextField();
        jTFnomComACT = new javax.swing.JTextField();
        jTFformaACT = new javax.swing.JTextField();
        jTFcumACT = new javax.swing.JTextField();
        jTFpresentacionACT = new javax.swing.JTextField();
        jTFloteACT = new javax.swing.JTextField();
        jTFfechaExpACT = new javax.swing.JTextField();
        jTFcantidadACT = new javax.swing.JTextField();
        jTFvalorUnitACT = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPbuscarACT = new javax.swing.JPanel();
        jLbuscarACT = new javax.swing.JLabel();
        jPactualizarACT = new javax.swing.JPanel();
        jLactualizarACT = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jTFconcentracionBORR = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTFrepresentanteBORR = new javax.swing.JTextField();
        jTFnoFacBORR = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTFfechaIngresoBORR = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTFproveedorBORR = new javax.swing.JTextField();
        jTFvalorTotaBORR = new javax.swing.JTextField();
        jTFnomGenBORR = new javax.swing.JTextField();
        jTFnomComBORR = new javax.swing.JTextField();
        jTFformaBORR = new javax.swing.JTextField();
        jTFcumBORR = new javax.swing.JTextField();
        jTFpresentacionBORR = new javax.swing.JTextField();
        jTFloteBORR = new javax.swing.JTextField();
        jTFfechaExpBORR = new javax.swing.JTextField();
        jTFcantidadBORR = new javax.swing.JTextField();
        jTFvalorUnitBORR = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPbuscarBORR = new javax.swing.JPanel();
        jLbuscarBORR = new javax.swing.JLabel();
        jPborrarBORR = new javax.swing.JPanel();
        jLborrarBORR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        jLabel3.setText("HOSPITAL EPN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel3.setBackground(new java.awt.Color(0, 134, 190));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INGRESOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        jPregresar.setBackground(new java.awt.Color(153, 204, 255));

        jLregresar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLregresar.setForeground(new java.awt.Color(255, 255, 255));
        jLregresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLregresar.setText("REGRESAR");
        jLregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLregresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPregresarLayout = new javax.swing.GroupLayout(jPregresar);
        jPregresar.setLayout(jPregresarLayout);
        jPregresarLayout.setHorizontalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLregresar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPregresarLayout.setVerticalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLregresar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 150, 30));

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos del Producto");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 10));

        jTFconcentracionCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFconcentracionCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFconcentracionCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Concentracion");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Representante");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jTFrepresentanteCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFrepresentanteCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFrepresentanteCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFnoFacCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnoFacCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFnoFacCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("No. Factura");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha de ingreso");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jTFfechaIngresoCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaIngresoCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFfechaIngresoCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));

        jLabel4.setText("Datos Generales");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Proveedor");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Valor Total");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nombre Genrico");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nombre Comercial");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Forma Farmaceutica");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jTFproveedorCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFproveedorCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFproveedorCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFvalorTotalCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorTotalCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFvalorTotalCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 250, -1));

        jTFnomGenCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFnomGenCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jTFnomComCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFnomComCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        jTFformaCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFformaCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jTFcumCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFcumCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTFpresentacionCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFpresentacionCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, -1));

        jTFloteCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFloteCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, -1));

        jTFfechaExpCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFfechaExpCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, -1));

        jTFcantidadCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFcantidadCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 250, -1));

        jTFvalorUnitCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorUnitCREARActionPerformed(evt);
            }
        });
        jPanel2.add(jTFvalorUnitCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("CUM/CUDIM");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Presentacion");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Lote");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Fecha exp.");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Cantidad");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Valor unitario");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("NUEVO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 350, 30));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CREAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "Representante", "No. Factura", "Fecha de ingreso", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Valor unitario", "Valor total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jTabbedPane1.addTab("Crear", jPanel2);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Datos del Producto");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel9.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 780, 10));

        jTFconcentracionBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFconcentracionBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFconcentracionBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 250, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Concentracion");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Representante");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jTFrepresentanteBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFrepresentanteBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFrepresentanteBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFnoFacBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnoFacBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFnoFacBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("No. Factura");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Fecha de ingreso");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jTFfechaIngresoBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaIngresoBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFfechaIngresoBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));

        jLabel27.setText("Datos Generales");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel9.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Proveedor");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Valor Total");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Nombre Genrico");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Nombre Comercial");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Forma Farmaceutica");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jTFproveedorBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFproveedorBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFproveedorBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFvalorTotalBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorTotalBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFvalorTotalBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 250, -1));

        jTFnomGenBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFnomGenBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 250, -1));

        jTFnomComBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFnomComBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 250, -1));

        jTFformaBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFformaBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 250, -1));

        jTFcumBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFcumBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, -1));

        jTFpresentacionBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFpresentacionBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 250, -1));

        jTFloteBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFloteBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 250, -1));

        jTFfechaExpBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFfechaExpBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 250, -1));

        jTFcantidadBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFcantidadBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 250, -1));

        jTFvalorUnitBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorUnitBUSActionPerformed(evt);
            }
        });
        jPanel9.add(jTFvalorUnitBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 250, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("CUM/CUDIM");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Presentacion");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 20));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Lote");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, 20));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("Fecha exp.");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 20));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Cantidad");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Valor unitario");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, 20));

        jPbuscar.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscar2.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscar2.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscarLayout = new javax.swing.GroupLayout(jPbuscar);
        jPbuscar.setLayout(jPbuscarLayout);
        jPbuscarLayout.setHorizontalGroup(
            jPbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPbuscarLayout.setVerticalGroup(
            jPbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 30));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "Representante", "No. Factura", "Fecha de ingreso", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Valor unitario", "Valor total"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jScrollPane3.setViewportView(jScrollPane4);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jPbuscar1.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscar1.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscar1.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscar1Layout = new javax.swing.GroupLayout(jPbuscar1);
        jPbuscar1.setLayout(jPbuscar1Layout);
        jPbuscar1Layout.setHorizontalGroup(
            jPbuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPbuscar1Layout.setVerticalGroup(
            jPbuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbuscar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 780, 30));

        jLbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscar.setText("BUSCAR");
        jPanel9.add(jLbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 30));

        jTabbedPane1.addTab("Buscar", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setText("Datos del Producto");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel10.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 10));

        jTFconcentracionACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFconcentracionACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFconcentracionACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Concentracion");
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Representante");
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jTFrepresentanteACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFrepresentanteACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFrepresentanteACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFnoFacACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnoFacACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFnoFacACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("No. Factura");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("Fecha de ingreso");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jTFfechaIngresoACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaIngresoACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFfechaIngresoACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));

        jLabel44.setText("Datos Generales");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel10.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("Proveedor");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("Valor Total");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 20));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setText("Nombre Genrico");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setText("Nombre Comercial");
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Forma Farmaceutica");
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jTFproveedorACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFproveedorACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFproveedorACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFvalorTotalACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorTotalACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFvalorTotalACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 250, -1));

        jTFnomGenACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFnomGenACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jTFnomComACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFnomComACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        jTFformaACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFformaACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jTFcumACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFcumACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTFpresentacionACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFpresentacionACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, -1));

        jTFloteACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFloteACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, -1));

        jTFfechaExpACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFfechaExpACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, -1));

        jTFcantidadACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFcantidadACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 250, -1));

        jTFvalorUnitACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorUnitACTActionPerformed(evt);
            }
        });
        jPanel10.add(jTFvalorUnitACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("CUM/CUDIM");
        jPanel10.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Presentacion");
        jPanel10.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setText("Lote");
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setText("Fecha exp.");
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 20));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("Cantidad");
        jPanel10.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Valor unitario");
        jPanel10.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "Representante", "No. Factura", "Fecha de ingreso", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Valor unitario", "Valor total"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jScrollPane5.setViewportView(jScrollPane6);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jPbuscarACT.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscarACT.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscarACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarACT.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscarACTLayout = new javax.swing.GroupLayout(jPbuscarACT);
        jPbuscarACT.setLayout(jPbuscarACTLayout);
        jPbuscarACTLayout.setHorizontalGroup(
            jPbuscarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPbuscarACTLayout.setVerticalGroup(
            jPbuscarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPbuscarACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 30));

        jPactualizarACT.setBackground(new java.awt.Color(153, 204, 255));

        jLactualizarACT.setForeground(new java.awt.Color(255, 255, 255));
        jLactualizarACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLactualizarACT.setText("ACTUALIZAR");

        javax.swing.GroupLayout jPactualizarACTLayout = new javax.swing.GroupLayout(jPactualizarACT);
        jPactualizarACT.setLayout(jPactualizarACTLayout);
        jPactualizarACTLayout.setHorizontalGroup(
            jPactualizarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLactualizarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPactualizarACTLayout.setVerticalGroup(
            jPactualizarACTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLactualizarACT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPactualizarACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 350, 30));

        jTabbedPane1.addTab("Actualizar", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setText("Datos del Producto");
        jPanel11.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel11.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 10));

        jTFconcentracionBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFconcentracionBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFconcentracionBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setText("Concentracion");
        jPanel11.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("Representante");
        jPanel11.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jTFrepresentanteBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFrepresentanteBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFrepresentanteBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jTFnoFacBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnoFacBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFnoFacBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setText("No. Factura");
        jPanel11.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("Fecha de ingreso");
        jPanel11.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 20));

        jTFfechaIngresoBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaIngresoBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFfechaIngresoBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, -1));

        jLabel61.setText("Datos Generales");
        jPanel11.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel11.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel62.setText("Proveedor");
        jPanel11.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel63.setText("Valor Total");
        jPanel11.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 20));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel64.setText("Nombre Genrico");
        jPanel11.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setText("Nombre Comercial");
        jPanel11.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("Forma Farmaceutica");
        jPanel11.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jTFproveedorBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFproveedorBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFproveedorBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jTFvalorTotaBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorTotaBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFvalorTotaBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 250, -1));

        jTFnomGenBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFnomGenBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jTFnomComBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFnomComBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        jTFformaBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFformaBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jTFcumBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFcumBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTFpresentacionBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFpresentacionBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, -1));

        jTFloteBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFloteBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, -1));

        jTFfechaExpBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFfechaExpBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, -1));

        jTFcantidadBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFcantidadBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 250, -1));

        jTFvalorUnitBORR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorUnitBORRActionPerformed(evt);
            }
        });
        jPanel11.add(jTFvalorUnitBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel67.setText("CUM/CUDIM");
        jPanel11.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel68.setText("Presentacion");
        jPanel11.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel69.setText("Lote");
        jPanel11.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel70.setText("Fecha exp.");
        jPanel11.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 20));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel71.setText("Cantidad");
        jPanel11.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel72.setText("Valor unitario");
        jPanel11.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "Representante", "No. Factura", "Fecha de ingreso", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Valor unitario", "Valor total"
            }
        ));
        jScrollPane8.setViewportView(jTable4);

        jScrollPane7.setViewportView(jScrollPane8);

        jPanel11.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 170));

        jPbuscarBORR.setBackground(new java.awt.Color(153, 204, 255));

        jLbuscarBORR.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscarBORR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbuscarBORR.setText("BUSCAR");

        javax.swing.GroupLayout jPbuscarBORRLayout = new javax.swing.GroupLayout(jPbuscarBORR);
        jPbuscarBORR.setLayout(jPbuscarBORRLayout);
        jPbuscarBORRLayout.setHorizontalGroup(
            jPbuscarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPbuscarBORRLayout.setVerticalGroup(
            jPbuscarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbuscarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel11.add(jPbuscarBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 30));

        jPborrarBORR.setBackground(new java.awt.Color(153, 204, 255));

        jLborrarBORR.setForeground(new java.awt.Color(255, 255, 255));
        jLborrarBORR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLborrarBORR.setText("BORRAR");

        javax.swing.GroupLayout jPborrarBORRLayout = new javax.swing.GroupLayout(jPborrarBORR);
        jPborrarBORR.setLayout(jPborrarBORRLayout);
        jPborrarBORRLayout.setHorizontalGroup(
            jPborrarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLborrarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPborrarBORRLayout.setVerticalGroup(
            jPborrarBORRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLborrarBORR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel11.add(jPborrarBORR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 350, 30));

        jTabbedPane1.addTab("Borrar", jPanel11);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLregresarMouseClicked

        JFmenuInventario regre = new JFmenuInventario();
        regre.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLregresarMouseClicked

    private void jTFvalorUnitCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorUnitCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorUnitCREARActionPerformed

    private void jTFcantidadCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadCREARActionPerformed

    private void jTFfechaExpCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpCREARActionPerformed

    private void jTFloteCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteCREARActionPerformed

    private void jTFpresentacionCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionCREARActionPerformed

    private void jTFcumCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumCREARActionPerformed

    private void jTFformaCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaCREARActionPerformed

    private void jTFnomComCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComCREARActionPerformed

    private void jTFnomGenCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenCREARActionPerformed

    private void jTFvalorTotalCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorTotalCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorTotalCREARActionPerformed

    private void jTFproveedorCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFproveedorCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFproveedorCREARActionPerformed

    private void jTFfechaIngresoCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaIngresoCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaIngresoCREARActionPerformed

    private void jTFnoFacCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnoFacCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnoFacCREARActionPerformed

    private void jTFrepresentanteCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFrepresentanteCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFrepresentanteCREARActionPerformed

    private void jTFconcentracionCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFconcentracionCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFconcentracionCREARActionPerformed

    private void jTFconcentracionBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFconcentracionBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFconcentracionBUSActionPerformed

    private void jTFrepresentanteBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFrepresentanteBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFrepresentanteBUSActionPerformed

    private void jTFnoFacBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnoFacBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnoFacBUSActionPerformed

    private void jTFfechaIngresoBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaIngresoBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaIngresoBUSActionPerformed

    private void jTFproveedorBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFproveedorBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFproveedorBUSActionPerformed

    private void jTFvalorTotalBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorTotalBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorTotalBUSActionPerformed

    private void jTFnomGenBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenBUSActionPerformed

    private void jTFnomComBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComBUSActionPerformed

    private void jTFformaBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaBUSActionPerformed

    private void jTFcumBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumBUSActionPerformed

    private void jTFpresentacionBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionBUSActionPerformed

    private void jTFloteBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteBUSActionPerformed

    private void jTFfechaExpBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpBUSActionPerformed

    private void jTFcantidadBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadBUSActionPerformed

    private void jTFvalorUnitBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorUnitBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorUnitBUSActionPerformed

    private void jTFconcentracionACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFconcentracionACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFconcentracionACTActionPerformed

    private void jTFrepresentanteACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFrepresentanteACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFrepresentanteACTActionPerformed

    private void jTFnoFacACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnoFacACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnoFacACTActionPerformed

    private void jTFfechaIngresoACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaIngresoACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaIngresoACTActionPerformed

    private void jTFproveedorACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFproveedorACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFproveedorACTActionPerformed

    private void jTFvalorTotalACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorTotalACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorTotalACTActionPerformed

    private void jTFnomGenACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenACTActionPerformed

    private void jTFnomComACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComACTActionPerformed

    private void jTFformaACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaACTActionPerformed

    private void jTFcumACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumACTActionPerformed

    private void jTFpresentacionACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionACTActionPerformed

    private void jTFloteACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteACTActionPerformed

    private void jTFfechaExpACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpACTActionPerformed

    private void jTFcantidadACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadACTActionPerformed

    private void jTFvalorUnitACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorUnitACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorUnitACTActionPerformed

    private void jTFconcentracionBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFconcentracionBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFconcentracionBORRActionPerformed

    private void jTFrepresentanteBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFrepresentanteBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFrepresentanteBORRActionPerformed

    private void jTFnoFacBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnoFacBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnoFacBORRActionPerformed

    private void jTFfechaIngresoBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaIngresoBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaIngresoBORRActionPerformed

    private void jTFproveedorBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFproveedorBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFproveedorBORRActionPerformed

    private void jTFvalorTotaBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorTotaBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorTotaBORRActionPerformed

    private void jTFnomGenBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenBORRActionPerformed

    private void jTFnomComBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComBORRActionPerformed

    private void jTFformaBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaBORRActionPerformed

    private void jTFcumBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumBORRActionPerformed

    private void jTFpresentacionBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionBORRActionPerformed

    private void jTFloteBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteBORRActionPerformed

    private void jTFfechaExpBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpBORRActionPerformed

    private void jTFcantidadBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadBORRActionPerformed

    private void jTFvalorUnitBORRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorUnitBORRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvalorUnitBORRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLactualizarACT;
    private javax.swing.JLabel jLborrarBORR;
    private javax.swing.JLabel jLbuscar;
    private javax.swing.JLabel jLbuscar1;
    private javax.swing.JLabel jLbuscar2;
    private javax.swing.JLabel jLbuscarACT;
    private javax.swing.JLabel jLbuscarBORR;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JPanel jPactualizarACT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPborrarBORR;
    private javax.swing.JPanel jPbuscar;
    private javax.swing.JPanel jPbuscar1;
    private javax.swing.JPanel jPbuscarACT;
    private javax.swing.JPanel jPbuscarBORR;
    private javax.swing.JPanel jPregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTFcantidadACT;
    private javax.swing.JTextField jTFcantidadBORR;
    private javax.swing.JTextField jTFcantidadBUS;
    private javax.swing.JTextField jTFcantidadCREAR;
    private javax.swing.JTextField jTFconcentracionACT;
    private javax.swing.JTextField jTFconcentracionBORR;
    private javax.swing.JTextField jTFconcentracionBUS;
    private javax.swing.JTextField jTFconcentracionCREAR;
    private javax.swing.JTextField jTFcumACT;
    private javax.swing.JTextField jTFcumBORR;
    private javax.swing.JTextField jTFcumBUS;
    private javax.swing.JTextField jTFcumCREAR;
    private javax.swing.JTextField jTFfechaExpACT;
    private javax.swing.JTextField jTFfechaExpBORR;
    private javax.swing.JTextField jTFfechaExpBUS;
    private javax.swing.JTextField jTFfechaExpCREAR;
    private javax.swing.JTextField jTFfechaIngresoACT;
    private javax.swing.JTextField jTFfechaIngresoBORR;
    private javax.swing.JTextField jTFfechaIngresoBUS;
    private javax.swing.JTextField jTFfechaIngresoCREAR;
    private javax.swing.JTextField jTFformaACT;
    private javax.swing.JTextField jTFformaBORR;
    private javax.swing.JTextField jTFformaBUS;
    private javax.swing.JTextField jTFformaCREAR;
    private javax.swing.JTextField jTFloteACT;
    private javax.swing.JTextField jTFloteBORR;
    private javax.swing.JTextField jTFloteBUS;
    private javax.swing.JTextField jTFloteCREAR;
    private javax.swing.JTextField jTFnoFacACT;
    private javax.swing.JTextField jTFnoFacBORR;
    private javax.swing.JTextField jTFnoFacBUS;
    private javax.swing.JTextField jTFnoFacCREAR;
    private javax.swing.JTextField jTFnomComACT;
    private javax.swing.JTextField jTFnomComBORR;
    private javax.swing.JTextField jTFnomComBUS;
    private javax.swing.JTextField jTFnomComCREAR;
    private javax.swing.JTextField jTFnomGenACT;
    private javax.swing.JTextField jTFnomGenBORR;
    private javax.swing.JTextField jTFnomGenBUS;
    private javax.swing.JTextField jTFnomGenCREAR;
    private javax.swing.JTextField jTFpresentacionACT;
    private javax.swing.JTextField jTFpresentacionBORR;
    private javax.swing.JTextField jTFpresentacionBUS;
    private javax.swing.JTextField jTFpresentacionCREAR;
    private javax.swing.JTextField jTFproveedorACT;
    private javax.swing.JTextField jTFproveedorBORR;
    private javax.swing.JTextField jTFproveedorBUS;
    private javax.swing.JTextField jTFproveedorCREAR;
    private javax.swing.JTextField jTFrepresentanteACT;
    private javax.swing.JTextField jTFrepresentanteBORR;
    private javax.swing.JTextField jTFrepresentanteBUS;
    private javax.swing.JTextField jTFrepresentanteCREAR;
    private javax.swing.JTextField jTFvalorTotaBORR;
    private javax.swing.JTextField jTFvalorTotalACT;
    private javax.swing.JTextField jTFvalorTotalBUS;
    private javax.swing.JTextField jTFvalorTotalCREAR;
    private javax.swing.JTextField jTFvalorUnitACT;
    private javax.swing.JTextField jTFvalorUnitBORR;
    private javax.swing.JTextField jTFvalorUnitBUS;
    private javax.swing.JTextField jTFvalorUnitCREAR;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
