package Vista;

public class reportes extends javax.swing.JFrame {

    public reportes() {
        initComponents();
        this.setLocationRelativeTo(this);
        CambiosColorBoton.configurarCambiosColor(jLregresar, jPregresar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPregresar = new javax.swing.JPanel();
        jLregresar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTFffechaEgresCREAR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFnomGenCREAR = new javax.swing.JTextField();
        jTFnomComCREAR = new javax.swing.JTextField();
        jTFformaCREAR = new javax.swing.JTextField();
        jTFitemCREAR = new javax.swing.JTextField();
        jTFpresentacionCREAR = new javax.swing.JTextField();
        jTFloteCREAR = new javax.swing.JTextField();
        jTFfechaExpCREAR = new javax.swing.JTextField();
        jTFcantidadCREAR = new javax.swing.JTextField();
        jTFobservacionesCREAR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPgenerarReporte = new javax.swing.JPanel();
        jLgenerarReporte = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFcumCREAR1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        jLabel3.setText("HOSPITAL EPN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel3.setBackground(new java.awt.Color(0, 134, 190));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REPORTES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        jPregresar.setBackground(new java.awt.Color(153, 204, 255));

        jLregresar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLregresar.setForeground(new java.awt.Color(255, 255, 255));
        jLregresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLregresar.setText("REGRESAR");
        jLregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLregresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPregresarLayout = new javax.swing.GroupLayout(jPregresar);
        jPregresar.setLayout(jPregresarLayout);
        jPregresarLayout.setHorizontalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLregresar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPregresarLayout.setVerticalGroup(
            jPregresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLregresar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 150, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Datos del Producto");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha  Preparacion");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jTFffechaEgresCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFffechaEgresCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFffechaEgresCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 250, -1));

        jLabel5.setText("Datos Generales");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tipo de inventario");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nombre Generico");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nombre Comercial");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Forma Farmaceutica");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jTFnomGenCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomGenCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFnomGenCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, -1));

        jTFnomComCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomComCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFnomComCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jTFformaCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFformaCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFformaCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jTFitemCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFitemCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFitemCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 250, -1));

        jTFpresentacionCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpresentacionCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFpresentacionCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, -1));

        jTFloteCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFloteCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFloteCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, -1));

        jTFfechaExpCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaExpCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFfechaExpCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, -1));

        jTFcantidadCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFcantidadCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 250, -1));

        jTFobservacionesCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFobservacionesCREARActionPerformed(evt);
            }
        });
        jPanel4.add(jTFobservacionesCREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Item");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Presentacion");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Lote");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Fecha exp.");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Cantidad");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Observaciones");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        jPgenerarReporte.setBackground(new java.awt.Color(153, 204, 255));

        jLgenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        jLgenerarReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLgenerarReporte.setText("GENERAR REPORTE");

        javax.swing.GroupLayout jPgenerarReporteLayout = new javax.swing.GroupLayout(jPgenerarReporte);
        jPgenerarReporte.setLayout(jPgenerarReporteLayout);
        jPgenerarReporteLayout.setHorizontalGroup(
            jPgenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLgenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPgenerarReporteLayout.setVerticalGroup(
            jPgenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLgenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPgenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 780, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("CUM/CUDIM");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jTFcumCREAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcumCREAR1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTFcumCREAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jCheckBox1.setText("Periodico");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jCheckBox2.setText("General");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de inventario", "Fecha de Preparacion", "Item", "CUM/CUDIM", "Nom Generico", "Nom Comercial", "Forma Farmaceutica", "Presentacion", "Lote", "Fehca exp", "Cantidad", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 780, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLregresarMouseClicked

        JFmenuInventario regre = new JFmenuInventario();
        regre.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLregresarMouseClicked

    private void jTFffechaEgresCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFffechaEgresCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFffechaEgresCREARActionPerformed

    private void jTFnomGenCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomGenCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomGenCREARActionPerformed

    private void jTFnomComCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomComCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomComCREARActionPerformed

    private void jTFformaCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFformaCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFformaCREARActionPerformed

    private void jTFitemCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFitemCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFitemCREARActionPerformed

    private void jTFpresentacionCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpresentacionCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpresentacionCREARActionPerformed

    private void jTFloteCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFloteCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFloteCREARActionPerformed

    private void jTFfechaExpCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaExpCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaExpCREARActionPerformed

    private void jTFcantidadCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadCREARActionPerformed

    private void jTFobservacionesCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFobservacionesCREARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFobservacionesCREARActionPerformed

    private void jTFcumCREAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcumCREAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcumCREAR1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLgenerarReporte;
    private javax.swing.JLabel jLregresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPgenerarReporte;
    private javax.swing.JPanel jPregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTFcantidadCREAR;
    private javax.swing.JTextField jTFcumCREAR1;
    private javax.swing.JTextField jTFestableCREAR;
    private javax.swing.JTextField jTFfechaExpCREAR;
    private javax.swing.JTextField jTFffechaEgresCREAR;
    private javax.swing.JTextField jTFformaCREAR;
    private javax.swing.JTextField jTFitemCREAR;
    private javax.swing.JTextField jTFloteCREAR;
    private javax.swing.JTextField jTFnomComCREAR;
    private javax.swing.JTextField jTFnomGenCREAR;
    private javax.swing.JTextField jTFobservacionesCREAR;
    private javax.swing.JTextField jTFpresentacionCREAR;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
